public class Player {
    public void playing(){
       string player1Name = 'Seyma';
       system.debug(player1Name);
       string player2Name = 'Zehra';
       system.debug(player2Name);
       string player3Name = 'Sukru';
       system.debug(player3Name);
       string player4Name = 'Ahmet';
       system.debug(player4Name);
       string player5Name = 'Elif';
       system.debug(player5Name);

        
    }
    
}
