public  class Demo12 {
    public void hosgeldin(){
        system.debug('hosgeldin uzayli...');
        string firsName = 'Seyma';
        system.debug(firsName);
        string lastName = 'Gundogdu';
        system.debug(lastName);
        Integer a = 2;
        Integer b = 3;
        Integer total = a + b;
        system.debug(total);
        system.debug('this is final');
        system.debug('Thank you Locol');
    }
 }
