cat sfCat = new cat();
sfCat.name = 'ginger';
sfcat.color = 'orange';
system.debug('sf cat '+ sfCat);

cat bath12Cat = new cat('fluuffy', 'white');
system.debug('batch 12  cat' + bath12Cat); 

cat bath12Cat2 = new cat('zuzu', 'black');
system.debug('batch 12  cat' + bath12Cat2); 

cat bath12Cat3 = new cat('honey', 'yellow');
system.debug('batch 12  cat' + bath12Cat3); 



system.debug('number of cats => ' + cat.countCat);

